### ISSUE TITLE
Question: Limine on non-x86 systems

### ISSUE THREAD

**Issue by paulstelian97** [48cf/limine-zig-template#4]
Is there a template for Limine running on ARM? Probably assuming a specific platform like the Raspberry Pi or the plain "virt" target on qemu, I guess (to avoid having too much trouble from platforms being too different?)

**Comment by 48cf** [comment]
The AArch64 Zig target is still a bit rusty from what I remember, but I'll take a look later to see if it's possible. The last time I tried it had trouble emitting code for a feature set equivalent to the one we currently use for x86_64.

**Comment by paulstelian97** [comment]
Any reasonable feature set would be fine by me (I want to expand my own OS to also support aarch64, and for the moment I'll just target the "virt" platform -- when I'm in a better spot I'll probably do more than that).

**Comment by 48cf** [comment]
I added support for aarch64 in e659a4d9d9de77e665207721dce69e0e14af2816 and riscv64 in f235818370c45d91d8108d8cc4c946d423617b9b.
